database:
  enable: false
  host: 127.0.0.1
  port: 3306
  user: ""
  password: ""
  database: ""

redis:
  enable: false
  host: 127.0.0.1
  port: 6379
  user:
  password:
  connect: 32
  timeout: 1000
  reconnectDelay: 1000

preferred-route:
  ip: 127.0.0.1
